- name: Create {{ app_name }} app directories
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    state: directory
    path: /opt/splunk/etc/apps/{{ app_name }}/local/

- name: Create {{ app_name }} app files
  become: yes
  become_user: "{{ splunk_user }}"
  copy:
    content: ''
    dest: /opt/splunk/etc/apps/{{ app_name }}/local/server.conf
    force: no

- name: Configure server.conf
  become: true
  become_user: "{{ splunk_user }}"
  blockinfile:
    path: /opt/splunk/etc/apps/{{ app_name }}/local/server.conf
    marker: "## {mark} ANSIBLE MANAGED BLOCK ##" 
    block: |
      [general]
      site = {{ splunk_site }}

      [shclustering]
      pass4SymmKey = {{ splunk_shcluster_password }}
      shcluster_label = {{ splunk_shcluster_label }}
  notify: 
    - restart Splunk

