- name: Create {{ cs_app_name }} app directories
  become: yes
  become_user: splunk
  file:
    state: directory
    path: /opt/splunk/etc/apps/{{ cs_app_name }}/local/

- name: Create {{ cs_app_name }} app files
  become: yes
  become_user: splunk
  copy:
    dest: /opt/splunk/etc/apps/{{ cs_app_name }}/local/server.conf
    content: ""
    force: no
    group: splunk
    owner: splunk

- name: Configure server.conf
  become: true
  become_user: splunk
  blockinfile:
    path: /opt/splunk/etc/apps/{{ cs_app_name }}/local/server.conf
    marker: "## {mark} ANSIBLE MANAGED BLOCK ##" 
    backup: yes
    block: |
      [general]
      site = {{ splunk_site }}

      [replication_port://{{ splunk_replication_port }}]

      [clustering]
      master_uri = https://{{ hostvars[cluster_master]['sys_ip'] }}:8089
      pass4SymmKey = {{ splunk_cluster_password }}
      mode = slave
  notify: 
    - restart Splunk
