---
# handlers file for splunk_deployment_server

- name: reload deploy-server
  become: yes
  become_user: "{{ splunk_user }}"
  command: /opt/splunk/bin/splunk reload deploy-server -auth admin:{{ splunk_admin_password }}
