---
- name: Create {{ cert_label }} certificate bundle
  become: yes
  become_user: "{{ splunk_user }}"
  shell: >
    cat
    {{ server_cert }}
    {{ server_key }}
    {{ server_int_ca_cert }}
    {{ server_root_ca_cert }}
    >
    {{ splunk_cert }}
  args:
    creates: "{{ splunk_cert }}"

- name: Set permissions on {{ cert_label }} certificate bundle
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    path: "{{ splunk_cert }}"
    state: file
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: 0600
