---
- name: Create {{ server_cert_dir }} directory for PKI files
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    path: "{{ server_cert_dir }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: "{{ pki_dir_mode }}"
    state: directory

- name: Install {{ cert_label }} certificate
  become: yes
  become_user: "{{ splunk_user }}"
  copy:
    src: "{{ local_store }}/{{ inventory_hostname }}/{{ ca_dir }}/{{ ca_int_dir }}/{{ ca_cert_dir }}/{{ server_cert_name }}"
    dest: "{{ server_cert_dir }}/{{ server_cert_name }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
    mode: "{{ pki_file_mode }}"
