---
- name: Create {{ fwd_outputs_app_name }} app directories
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    state: directory
    path: /opt/splunk/etc/deployment-apps/{{ fwd_outputs_app_name }}/local/

- name: Create {{ fwd_outputs_app_name }} app files
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    state: touch
    path: /opt/splunk/etc/deployment-apps/{{ fwd_outputs_app_name }}/local/outputs.conf

- name: Configure outputs.conf
  become: true
  become_user: "{{ splunk_user }}"
  blockinfile:
    path: /opt/splunk/etc/deployment-apps/{{ fwd_outputs_app_name }}/local/outputs.conf
    marker: "## {mark} ANSIBLE MANAGED BLOCK ##" 
    block: |
        [tcpout]
        sslCertPath=$SPLUNK_HOME/etc/deployment-apps/{{ fwd_cert_app_name }}/local/certs/forwarder.outputs.cert.pem
        sslVerifyServerCert = true
        sslRootCAPath==$SPLUNK_HOME/etc/deployment-apps/{{ fwd_cert_app_name }}/local/ca/ca.cert.pem
  notify: 
    - restart Splunk
