---
- name: Create deployment-apps directories
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    state: directory
    dest: "/opt/splunk/etc/deployment-apps/{{ item }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
  with_items: 
    - "{{  lookup ('filetree', '../templates/deployment-apps/' ) | selectattr('state', 'match', 'directory') | map(attribute = 'path') | list  }}"

- name: Create deployment-apps files
  become: yes
  become_user: "{{ splunk_user }}"
  template:
    src: ../templates/deployment-apps/{{ item }}
    dest: "/opt/splunk/etc/deployment-apps/{{ item }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
  with_items:
    - "{{  lookup ('filetree', '../templates/deployment-apps/' ) | selectattr('state', 'match', 'file') | map(attribute = 'path') | list  }}"
  notify: reload deploy-server
