---
- block:
  - name: Change admin password from default
    become: yes
    become_user: "{{ splunk_user }}"
    shell: /opt/splunk/bin/splunk edit user admin -password {{ splunk_admin_password }} -auth admin:changeme
    notify: restart Splunk
  
  - name: Disable first-time message on UI
    become: yes
    become_user: "{{ splunk_user }}"
    file:
      state: touch
      path: /opt/splunk/etc/.ui_login

  when: splunk_installed.rc != 0
