---
- name: Open up ports in firewalld
  become: yes
  firewalld:
    port: "{{ item }}"
    zone: public
    state: enabled
    permanent: true
    immediate: true
  loop:
    - "{{ splunk_web_port }}/tcp"
    - "{{ splunk_sh_replication_port }}/tcp"
