- name: Create {{ app_name }} app directories
  become: yes
  become_user: splunk
  file:
    state: directory
    path: /opt/splunk/etc/apps/{{ app_name }}/local/

- name: Create {{ app_name }} app files
  become: yes
  become_user: splunk
  file:
    state: touch
    path: /opt/splunk/etc/apps/{{ app_name }}/local/server.conf

- name: Configure server.conf
  become: true
  become_user: splunk
  blockinfile:
    path: /opt/splunk/etc/apps/{{ app_name }}/local/server.conf
    marker: "## {mark} ANSIBLE MANAGED Search Head BLOCK ##" 
    block: |
      [general]
      site = {{ splunk_site }}

      [clustering]
      mode = searchhead
      pass4SymmKey = {{ splunk_cluster_password }}
      master_uri = clustermaster:one

      [clustermaster:one]
      master_uri = https://{{ hostvars[cluster_master]['sys_ip'] }}:8089
      multisite = true
  notify: 
    - restart Splunk

