- name: Create {{ tcp_inputs_app_name }} app directories
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    state: directory
    path: /opt/splunk/etc/master-apps/{{ tcp_inputs_app_name }}/local/

- name: Create {{ tcp_inputs_app_name }} app files
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    state: touch
    path: /opt/splunk/etc/master-apps/{{ tcp_inputs_app_name }}/local/inputs.conf

- name: Configure inputs.conf
  become: true
  become_user: "{{ splunk_user }}"
  blockinfile:
    path: /opt/splunk/etc/master-apps/{{ tcp_inputs_app_name }}/local/inputs.conf
    marker: "## {mark} ANSIBLE MANAGED BLOCK ##" 
    block: |
      [splunktcp-ssl://{{ splunk_splunktcp_port }}]
      disabled = 0

      [SSL]
      requireClientCert = true
  notify: 
    - apply cluster-bundle
