---
- name: Create master-apps directories
  become: yes
  become_user: "{{ splunk_user }}"
  file:
    state: directory
    dest: "/opt/splunk/etc/master-apps/{{ item.path }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
  loop: "{{  lookup ('filetree', '../templates/master-apps/' ) | selectattr('state', 'match', 'directory' ) | list }}"
  loop_control:
    label: "{{ item.path }}"

- name: Create master-apps files
  become: yes
  become_user: "{{ splunk_user }}"
  template:
    src: "{{ item.src }}"
    dest: "/opt/splunk/etc/master-apps/{{ item.path }}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}"
  loop: "{{  lookup ('filetree', '../templates/master-apps/' ) | selectattr('state', 'match', 'file' ) | list }}"
  loop_control:
    label: "{{ item.path }}"
  notify: apply cluster-bundle
